name: Main

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: A job to test the action
    steps:
    - uses: actions/checkout@v1
    - name: Checkout and Node setup
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: npm ci
    - name: Extract info
      uses: ./ # Uses an action in the root directory
      id: extract
      with:
        filter_push: '.commits'
        filter_pull_request: '.pull_request.commits'
    # Use the output from the `infos` step
    - name: Show output
      run: |
        echo "value: ${{ steps.extract.outputs.value }}"
        echo "branch: ${{ steps.extract.outputs.branch }}"
        echo "pull_request: ${{ steps.extract.outputs.pull_request }}"